### ISSUE TITLE
wrong 

### ISSUE THREAD

**Issue by RedTeaDev** [samueltangz/ctf-archive-created#1]
![圖片](https://user-images.githubusercontent.com/51795815/99065108-dd8ff300-25e1-11eb-8b69-abd016f225e6.png)
![uaaaaaaanknown](https://user-images.githubusercontent.com/51795815/99065164-ee406900-25e1-11eb-884f-2a336b143dc0.png)

**Comment by samueltangz** [comment]
Not reproducible. I only count the teams who solved at least one challenge.

**Comment by RedTeaDev** [comment]
It total of 84 team, but the file said it 74 team only??
